### ISSUE TITLE
Bcbio small rna analysis

### ISSUE THREAD

**Issue by ahsen1402** [bcbio/bcbio-nextgen#2334]
Hi All, Today I run small rna seq pipeline with the following template:

upload:
  dir: /sc/orga/projects/stolog01a/bcbio_analysis/upload
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      species: hsa
    description: data
    genome_build: hg38

I wanted to skip trimming which I have already done myself. First does the yaml file above skips trimming because in the error atropos.py is part of the error (see below). Anyhow I get the following error:

[2018-03-15T05:31Z] QC: exosomes_1 atropos
Traceback (most recent call last):
  File "software/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "software/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 335, in smallrnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 37, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
  return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 199, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 151, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File "software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/atropos.py", line 6, in run
    with open(data["log_trimming"]) as inh:
IOError: [Errno 2] No such file or directory: 'bcbio_analysis/sample_info/work/trimmed/exosomes_1/exosomes_1.log'

Any ideas? Looks like some issue with multitasking. I had such a hard time to install this on the cluster and now this error drives me crazy.

**Comment by chapmanb** [comment]
Thanks much for the detailed report and apologies about the issue. It looks like the code is looking for an atropos log file which doesn't exist because you skipped trimming. I pushed a fix to the latest development version which should correctly skip this check. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run your pipeline in place it should pick up where it left off and correctly skip this step. Hope this gets things working for you.

**Comment by ahsen1402** [comment]
Thank you so much. I tried to upgrade but i got the following error:

Collecting bcbio-nextgen from git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/chapmanb/bcbio-nextgen.git to /tmp/pip-build-DCiVdh/bcbio-nextgen
error:  while accessing https://github.com/chapmanb/bcbio-nextgen.git/info/refs

fatal: HTTP request failed
Command "git clone -q https://github.com/chapmanb/bcbio-nextgen.git /tmp/pip-build-DCiVdh/bcbio-nextgen" failed with error code 128 in None
Collecting bcbio-nextgen from git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen
  Cloning https://github.com/chapmanb/bcbio-nextgen.git to /tmp/pip-build-k_zZuI/bcbio-nextgen
error:  while accessing https://github.com/chapmanb/bcbio-nextgen.git/info/refs

fatal: HTTP request failed
Command "git clone -q https://github.com/chapmanb/bcbio-nextgen.git /tmp/pip-build-k_zZuI/bcbio-nextgen" failed with error code 128 in None
Traceback (most recent call last):
  File "/sc/orga/projects/stolog01a/software/bin/bcbio_nextgen.py", line 222, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/sc/orga/projects/stolog01a/software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 63, in upgrade_bcbio
    "git+%s%s#egg=bcbio-nextgen" % (REMOTES["gitrepo"], git_tag)]], anaconda_dir)
  File "/sc/orga/projects/stolog01a/software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 118, in _pip_safe_ssl
    subprocess.check_call(cmd)
  File "/sc/orga/projects/stolog01a/software_data/bcbio/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/sc/orga/projects/stolog01a/software_data/bcbio/anaconda/bin/pip', 'install', '--upgrade', '--no-deps', 'git+https://github.com/chapmanb/bcbio-nextgen.git#egg=bcbio-nextgen']' returned non-zero exit status 1

**Comment by ahsen1402** [comment]
Hi,
I tried this but the error persists unfortunately here is a log:

Traceback (most recent call last):
  File " software/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File " software/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 334, in smallrnaseqpipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 37, in generate_parallel
    qced = run_parallel("pipeline_summary", to_analyze)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
File " software_data/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 52, in wrapper
    return apply(f, *args, **kwargs)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 199, in pipeline_summary
    return qcsummary.pipeline_summary(*args)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 68, in pipeline_summary
    data["summary"] = _run_qc_tools(work_bam, work_data)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 151, in _run_qc_tools
    out = qc_fn(bam_file, data, cur_qc_dir)
  File " software_data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/atropos.py", line 5, in run
    if "log_trimming" in data and utils.file_exists(data["log_trimming"]):
NameError: global name 'utils' is not defined


This error is new i believe "NameError: global name 'utils' is not defined". Any more guidance?
