### ISSUE TITLE
IOError: Could not prepare index seq for mm10 by any method

### ISSUE THREAD

**Issue by bug1303** [bcbio/bcbio-nextgen#2667]
I tried to install bcbio on a Linux system using:
`python bcbio_nextgen_install.py --cores 6 --tooldir path-to-tools --datatarget rnaseq --genomes mm10 --aligners star  --distribution ubuntu    path-to-bcbiodata`

Install ran for a while and looked fine until it got to the genome data:

[bcbio_install_log_err.txt](https://github.com/bcbio/bcbio-nextgen/files/2831569/bcbio_install_log_err.txt)

Any hints on what I should try instead?

The bcbiodata dir now contains:
18G     anaconda
4.0K    config
12K     galaxy
16K     genomes
364K    manifest

**Comment by bug1303** [comment]
Thanks for your quick reply and the bug fix.
It didn't work with just re-running the install command, but that might be due to me trying something else in between, so I tried with a fresh full install again.

I got quite a bit further, it did download the genome (ftp://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/chromFa.tar.gz) and created the mm10.fa / mm10.fa.fai / mm10.dict

Then STAR "finished successfully"

Preparing genome mm10 with index rtg
Formatting FASTA data
Processing "path-to-bcbiodata/genomes/Mmusculus/mm10/seq/mm10.fa"

This looks like a genome reference, but is not recognized. You should enable sex-aware processing by manually installing an appropriate reference.txt containing chromosome metadata.  See the user manual for more information.

[...]
Running GGD recipe: mm10 transcripts 2018-10-10_92
--2019-02-05 16:10:04--  https://s3.amazonaws.com/biodata/annotation/mm10-rnaseq-2018-10-10_92.tar.xz

[ this is fetched successfully, but then ]


> Running GGD recipe: mm10 rmsk 20180319
> Traceback (most recent call last):
>   File "path-to-bcbiodata/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "path-to-bcbiodata/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 105, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "path-to-bcbiodata/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 366, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
>     configure_instance(options, actions)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 269, in configure_instance
>     setup_biodata(options)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 251, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 325, in install_data
>     env.galaxy_home, env.tool_data_table_conf_file, env.cores, approaches)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 349, in install_data_local
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 495, in _prep_genomes
>     _index_to_galaxy(env, org_dir, ref_file, gid, genome_indexes, manager.config)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 543, in _index_to_galaxy
>     galaxy.prep_locs(env, gid, indexes, config)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/galaxy.py", line 123, in prep_locs
>     update_loc_file(env, ref_index_file, str_parts)
>   File "path-to-bcbiotools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/galaxy.py", line 105, in update_loc_file
>     out_handle.write(line + "\n")
> UnboundLocalError: local variable 'line' referenced before assignment
> Traceback (most recent call last):
>   File "bcbio_nextgen_install.py", line 287, in <module>
>     main(parser.parse_args(), sys.argv[1:])
>   File "bcbio_nextgen_install.py", line 44, in main
>     subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['path-to-bcbiodata/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--cores', '6', '--tooldir', 'path-to-bcbiotools/', '--datatarget', 'rnaseq', '--genomes', 'mm10', '--aligners', 'star', '--distribution', 'ubuntu', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for continuing to work on this and apologies about the continued issues. This was another bug I introduced during the refactoring which just got fixed by @pprieto: https://github.com/chapmanb/cloudbiolinux/pull/282 If you can manage to remove the existing cloudbiolinux and re-run it should hopefully pick up here and finish successfully for you this time. I appreciate all the patience working through these issues and sorry about the extra problems.

**Comment by bug1303** [comment]
Thanks for the quick reply. I had seen pprieto's PR right after I posted my question and was hoping it would do the fix.

I tried with your previously suggested approach of `rm -rf tmpbcbio-install` and re-running the install command. However, it then fails on a numpy import. `ImportError: No module named numpy`

But before that, I get 

    The following packages will be SUPERSEDED by a higher-priority channel:
    [...]
      numpy              conda-forge::numpy-1.15.4-py27_blas_o~ --> pkgs/main::numpy-1.15.4-py27h7e9f1db_0

And it downloads other packages then, but not the numpy one?

I attach the full log:
[bcbio_install_log_err2.txt](https://github.com/bcbio/bcbio-nextgen/files/2833215/bcbio_install_log_err2.txt)

**Comment by bug1303** [comment]
Unfortunately not, seems I killed my numpy there... 
I still get the `ImportError: No module named numpy` if I try the upgrade command.

**Comment by chapmanb** [comment]
Sorry about this issue, I'm not sure what happened here but you hopefully can fix that with:
```
path-to-bcbiodata/anaconda/bin/conda install -c conda-forge -y 'numpy=1.15*'
```
and then bcbio should be operational again to run the upgrade command. Hope this fixes it for you.

**Comment by bug1303** [comment]
Thanks for the help, that seems to have done the trick!

> bcbio-nextgen data upgrade complete.
> Upgrade completed successfully.
