### ISSUE TITLE
Bio.SeqIO issue in biopython 1.77

### ISSUE THREAD

**Issue by choosehappy** [bcbio/bcbio-nextgen#3277]
Just installed and ran through the RNA-seq pipeline, encountered this error:

```
[2020-06-25T14:16Z] Converting /bcbio/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf to FASTA format.
Traceback (most recent call last):
  File "/bcbio/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/bcbio/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 254, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 226, in quantitate_expression_parallel
    run_parallel("run_salmon_index", [to_index])
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 206, in apply_async
    result = ImmediateResult(func)
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 570, in __init__
    self.results = batch()
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 76, in run_salmon_index
    return salmon.run_salmon_index(*args)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 149, in run_salmon_index
    salmon_index(gtf_file, data, salmon_dir)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 169, in salmon_index
    kmersize = sailfish.pick_kmersize(files[0])
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/sailfish.py", line 199, in pick_kmersize
    readlength = fastq.estimate_read_length(fq)
  File "/bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/fastq.py", line 293, in estimate_read_length
    in_handle.close()
AttributeError: 'FastqPhredIterator' object has no attribute 'close'
```

i opened up /bcbio/anaconda/lib/python3.6/site-packages/bcbio/bam/fastq.py, saw this:
```
def estimate_read_length(fastq_file, quality_format="fastq-sanger", nreads=1000):
    """
    estimate average read length of a fastq file
    """

    in_handle = SeqIO.parse(open_fastq(fastq_file), quality_format)
    read = next(in_handle)
    average = len(read.seq)
    for _ in range(nreads):
        try:
            average = (average + len(next(in_handle).seq)) / 2
        except StopIteration:
            break
    in_handle.close()
    return average

```
and simply commented out the close operation like this:
```
def estimate_read_length(fastq_file, quality_format="fastq-sanger", nreads=1000):
    """
    estimate average read length of a fastq file
    """

    in_handle = SeqIO.parse(open_fastq(fastq_file), quality_format)
    read = next(in_handle)
    average = len(read.seq)
    for _ in range(nreads):
        try:
            average = (average + len(next(in_handle).seq)) / 2
        except StopIteration:
            break
#    in_handle.close()
    return average

```

and things worked fine after that :  )

maybe FastqPhredIterator no longer has a close method associated with it?

**Comment by naumenko-sa** [comment]
Hi @choosehappy !

Thanks for reporting!
This function works for me, and `in_handle` has `close()` attribute.

What is your biopython version?
```bash
conda list | grep biopython
biopython                 1.76             py36h516909a_0    conda-forge
```

you may also try if it works in (bcbio) python for you:
```python
>>> from Bio import SeqIO
>>> from bcbio.bam.fastq import open_fastq
>>> in_handle = SeqIO.parse(open_fastq("test_1.fq.gz"), "fastq-sanger")
>>> read = next(in_handle)
>>> in_handle.close()
```

Sergey

**Comment by choosehappy** [comment]
```
root@0fe8d464e16e:/# /bcbio/anaconda/bin/conda list | grep biopython
biopython                 1.77             py36h8c4c3a4_0    conda-forge


```

error exists directly in python:

![image](https://user-images.githubusercontent.com/9681868/85828833-894aba80-b789-11ea-948a-8d229065de93.png)

**Comment by gabeng** [comment]
Same issue here with a new install. Downgrading biopython to 1.76 removed the error message:
```
/usr/local/share/bcbio-nextgen/anaconda/bin/conda install -c conda-forge -c bioconda biopython=1.76
```

@choosehappy Are you able to finish your rnaseq analysis? I assume that you made a recent installation. I end up with errors like this:
```
[2020-06-27T13:46Z] Loading tximport.
[2020-06-27T13:46Z] Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
[2020-06-27T13:46Z] Execution halted
[2020-06-27T13:46Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio-nextgen/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/bioinf-data/bcbio/work/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/bioinf-data/bcbio/work/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/bioinf-data/bcbio/work/bcbiotx/tmpbgyu1qro/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/bioinf-data/bcbio/work/bcbiotx/tmp4qr6l5zr/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
Execution halted
' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 261, in rnaseqpipeline
    samples = rnaseq.combine_files(samples)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 482, in combine_files
    tximport = load_tximport(data)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 549, in load_tximport
    do.run([rcmd, "--vanilla", "-e", render_string], f"Loading tximport.")
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio-nextgen/anaconda/bin/Rscript --vanilla -e library(tidyverse);salmon_files = list.files("/bioinf-data/bcbio/work/salmon", pattern="quant.sf", recursive=TRUE, full.names=TRUE);tx2gene = readr::read_csv("/bioinf-data/bcbio/work/inputs/transcriptome/tx2gene.csv", col_names=c("transcript", "gene")); samples = basename(dirname(salmon_files));names(salmon_files) = samples;txi = tximport::tximport(salmon_files, type="salmon", tx2gene=tx2gene, countsFromAbundance="lengthScaledTPM");readr::write_csv(txi$counts %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/bioinf-data/bcbio/work/bcbiotx/tmpbgyu1qro/tximport-counts.csv");readr::write_csv(txi$abundance %>% as.data.frame() %>% tibble::rownames_to_column("gene"), "/bioinf-data/bcbio/work/bcbiotx/tmp4qr6l5zr/tximport-tpm.csv");
Error in library(tidyverse) : there is no package called \u2018tidyverse\u2019
Execution halted
' returned non-zero exit status 1.
```

**Comment by choosehappy** [comment]
yes,brand new install

and yes mine finished with no additional issues after correcting this small issue and this one:

https://github.com/bcbio/bcbio-nextgen/issues/3278

the latter one clearly indicates that tidyverse was successfully installed, not sure why you would be in that situation

**Comment by naumenko-sa** [comment]
Thanks @gabeng and @choosehappy for digging into the issue!
I think for now we'd pin biopython=1.76 and follow the comments in biopython.
S

**Comment by naumenko-sa** [comment]
Hi again @gabeng  and @choosehappy !

I've fixed the handle in `bcbio/bam/fastq` and reverted the biopython pinning.
Please let me know if that fixed the issue for you.

Sergey

**Comment by peterjc** [comment]
The fix makes sense - I still don't understand how the old code might have worked on older Biopython 🤷

**Comment by peterjc** [comment]
Thanks @chris-rands for the explanation: https://github.com/biopython/biopython/issues/3015#issuecomment-651356739

I'd missed the fact the using a generator functions means you automatically have a .close() method: https://docs.python.org/3/reference/expressions.html#generator.close
